FROM golang:1.12.4 AS builder
WORKDIR /src
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 go build \
    -installsuffix 'static' \
    -o /cassandra-init-rackdc .

FROM scratch
COPY --from=builder /cassandra-init-rackdc /cassandra-init-rackdc

ENTRYPOINT ["/cassandra-init-rackdc"]
